spring:
  jackson:
    # snake case style for response json
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: true
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

sa-token:
  token-style: uuid
  is-log: true

alipay:
  # 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
  APPID: 902100012269689
  # 商户私钥，您的PKCS8格式RSA2私钥
  RSA_PRIVATE_KEY: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQChPNqM/5/k4JnyO8YAZI38c0y1pjDO3umzUb+Lzz6S/0GFp8K8/yPhkzbXWn80vbQBu7lQR/Ab1U2mKwa2RV6yDmgE3ILb/pHoZYFLieH+u9P6pN1kNpEciqWE49UGC7klhuBtNgFXplJbwtddbW99CKjPmK5v+OMFTQ6eVFCrzYjf0eEXsQOq7sJUhWz6deu1Dh2DLi4CYh4boLhR+sEXbsFqyPgLwenCffygmnswJfogRY6lzyzNCGmG9TWrcmgcY5IxHRbl9g8ne/yBo9F9YlW5Kczlyyu9hEGzxLJZeHW1pzKXdZVoqr/J7c2xonwQq3oul9AuQBRJgECtbXVRAgMBAAECggEAKXy+A2+21a6RDgohTXKSMjX8s/S6NFCZM4HCVpgR0sMJOfnLmtPPiLhXcRwhBRIW4idKbITGHHNLEomZpYa98fTRAQc4SKD9LB4KIcStuNzdk22eZa3AsuZd5o60/mQ/1I8a6h7uQ35RTLkarzh8amCzBw+TOs6Ao5mLPGQXiczlcCp4yboixB0TlIkSIsshINbIP2S4AELIx+wRWYPvldUIlBJkNdJrNg7TAwd46OnJaNVwK2kTy4tQtW6fVckkmVLV2Ngn4p0R4oT9xzn+NLVosKQ5b7aJe+XXcr2uqf3lfym2VbNrucOJaMJ2uKiRmdMCpXBEL7p13jjuS30BEQKBgQDMK5hxVNJkev7Qhws1Ko4pyKUxFDvfFWX7dMa73g7tfL9yY7k7FqQi0eYm/uA/rsLux0IKCeWJyw46uicqYS/Z4mPZaBoK+8wvkG4o3/XshCFpFWumYvYX99ZTjtr9oZFfofNG1LbaHdoF1bL6/ZObmR8r9W/2KrT409RrYCJ7NQKBgQDKKzNVncC4/c+8GPqIwppCQ/nnAtOmy2wv2UFZv1Y+ud9pXYTH1tIB5W81aXVurN7PvK4vQ0f/7/iCUMEoqNDy9jF3yMi9YtL76L7pFEkN96KUKbuo16J9l+8BtDDWtsVQ32pr3kmSc71iCQ9tkIeftp3VKW3nOLaTustLwRM5LQKBgERjVeygPNjrWe7/TQHB/1x/mNWXsXZH9KEFvIuxFc72uinWvXTNYK1JIY5uUS8Dmsfgdn5mUjyVh26ka/oGE8En08o+1HpZXUuRVVTbr8RJfed1BVn2S/g7S88xSqkqNUeTN6nCFn15Ak5yBkGMLqUv5QEUdSw/od63Fa/hw6sBAoGAG2VpSnPbNvZmHTZBVSER6GLvzYdLiTHN0lodifzswglMJiofITmSMeGWhWVqHXpdo0cNT6hNbHhnc7lfw5PE5PfJ0lKqKUfoEW0D2e/+yl7BcFSLcqDuCxj4sYFqkN4ptQDhmgaAb9ExW8Sgi5dnWZRUpRs9InVEAJbyj6x1X20CgYBCgTt9uG6FLOlF4FAXnB0V/8Y/IOszukR1YuzkHbqaHovXh9uvO5bF/BdwIBkkOIR+YTaTSftefD5ja+iEkah5ut7Nr2KIL7yQKuePZJoekbAVKI/y+iZwArjn4zgef2wnCRrunkMB9YtyI92kupy8wra6zjCrIVSD6uP0f96a/g==
  # 支付宝支付公钥
  ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmPYgDnWRR7Ge9xvHPaaKIP/hBVnPGby9uJT4gzDld/HSrc9dGA1PNRxTcT2vTO2rjNM4/P7hNUM16DYi6iRXQM3bB4toxBNeIoLMHxLI46O3JY1euoHXWD+369279Y4dKptaeXJZG6NgR+jKP++R9UnIDheGg/z+E9IM98tbJjiO2MFx+nUMVj81nDfcg/Wl3GBRf6zhiwaQw/l2aeD2Xtax71rg9aprcMx1DS+hxa1m/DhCLfvv9mwUkd0+fRggWvNbcrAKghuSBMOWYmbv/7gInmgNOLYLjQfsH0JG02MTNLnjmOBo5tAC6aiTbcRVfkIQWTHteHnbgGperhirtwIDAQAB
  # 异步回调地址 必须外网能够访问（这里需要配置内网穿透），当支付成功后会调用该API
  notify_url: http://b5x773.natappfree.cc
  # 同步回调地址 必须外网能够访问
  return_url:
  # 网关（注意沙箱网关和正式网关的区别，这里填写沙箱环境下的网关）
  URL: https://openapi.alipaydev.com/gateway.do
  # 编码
  CHARSET: UTF-8
  # 返回数据格式
  FORMAT: json
  # 日志地址
  log_path: /log
  # RSA2
  SIGNTYPE: RSA2
