spring:
  jackson:
    # snake case style for response json
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: true
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

sa-token:
  token-style: uuid
  is-log: true

alipay:
  # 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
  APPID: 902100012269689
  # 商户私钥，您的PKCS8格式RSA2私钥
  RSA_PRIVATE_KEY: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDB9GHiPtcvjipYDtx/w+hOZcw/8PRFfo0FRMSMVPU6dqjYpubIAyM8YLom8w5EHlpOTXsw862oJe4W4m0joQbQ/y2Uzpk/pgXBZUt49XMcu9+EG0cO5/XcQa3Eu46DGjA0DmTfU78YsEHaHIm+PehHvh7mG+cBicKTGIljDCZLL8hql3oTt4MY9eaL1J0tpQJq7W6QA6Ns9eVK6Nc6mm1DNafgQ7VDPrtaPd3Qn2ZWzz2nu8HMDtqTGW9La3ddlGi6ahVQT671LGOwZ5ff4YLWwQPb4TnJ2WRqh3T0bpyR4gj4tddvPdx9bXX7aLLc8Kj1FncdpQBlGrS2orFGfHynAgMBAAECggEBAI7fCkuypqitPJvpNpwXH8TAUBi50fZvJko/Qdltq8cJKY+OQmoLhaUwS2/tkxCymysbACgrGDzI0/2fhW29bFv/3P/EwDaWgZ7YkyPjCoycCCY0Qb/FNuKsruhAkNYaMG/oOn4YHqh9DcUxSHYO/E/8yJ4Q57XGWMIqTOndRUgT/hPWfiDN7PrRO+eZuMs9z3w/FMv72cCyCPNbiuSqBKweXfs9U3UsfbXbNDEgkVTWfdEV/ak9y6XMuEUnRdVXBFUJPBIbn1ozcSSVnblOWh83dfJ4VdIIrynnud4VfAbQWLlT3g9snHET6VlvbgsTMQXPuzTSfZILEz3ekhSPJQECgYEA6ZPPte9tWWvmuzkkZb6Dn9QeHmHYH9Asn6rYY/5DQD/BqzS/jnuCKP/yNrLEphjmmvFoNBhmMmJBlaa0f+cH5THBfNvYkwunAL9d/n2/G7kwdHDrHzMuD8D761JoycdAlErGMTGSYuwPtFPeA4olzYJNEz3xMKCsbB/bLKo19wcCgYEA1JLWWWN/0W7KymHzsBRKHiENSYvQkl9m0j/N8Mjh2UJ6Jfswleoe2ZFrRKFnQ2JfPEjl4E2M2BwC+61/pxx1rnchMo8bvnH67BKqAixXilFrB/kWLIVTh890ptpB7NvUxL5UUl/5xElaDYU3tXCxououdPeerCEe/Re8ILWjRWECgYEAvk16Vp2qtsdNpk5JFEgjD04P9+r53fmK0c+tG9Ll0evgC3AffaOtCWB2ZBBEXZs+DxEOOBuE8BnTm2zF9MszSI3AOc0YZ71/pAFGQHkNAjZgfw4c0j+tkJJH7ZMn4vXe7LL7RMtBnCz+IoqOAM5GPGikCUBXSKovsKxHst0+uHMCgYAcX+1UyT9KiWtwUFri6hJqqybG5m7U2v8ymWm39liPU5xSbZEysamkiRC0fIb4K61isqhcpH1ka3jKd4JOoDHlM+muggPGDBjeYi9nUtvsjqmmysz27GUV/88mZoPeRgnEqVNAG6ePV+s5Wsrw4TYU9QV2f4cimtk0F3L5OsWsgQKBgAT8a7LKlgK03gklBmPMy3ZXztMQCkqeG60OnwI17k96Ag6HI0nphaE82jd1e7A3GhwIilG1ySmVUe4U+s0I8hktAU9jk7oWSk2mlfC6DS/IaPcoEPDimPQ0smPDLpXNJqhGD195N90LZ5fUHSAfkroLggu4kFYa9kZE/gLE3W6q"
  # 支付宝支付公钥
  ALIPAY_PUBLIC_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmPYgDnWRR7Ge9xvHPaaKIP/hBVnPGby9uJT4gzDld/HSrc9dGA1PNRxTcT2vTO2rjNM4/P7hNUM16DYi6iRXQM3bB4toxBNeIoLMHxLI46O3JY1euoHXWD+369279Y4dKptaeXJZG6NgR+jKP++R9UnIDheGg/z+E9IM98tbJjiO2MFx+nUMVj81nDfcg/Wl3GBRf6zhiwaQw/l2aeD2Xtax71rg9aprcMx1DS+hxa1m/DhCLfvv9mwUkd0+fRggWvNbcrAKghuSBMOWYmbv/7gInmgNOLYLjQfsH0JG02MTNLnjmOBo5tAC6aiTbcRVfkIQWTHteHnbgGperhirtwIDAQAB"
# 异步回调地址 必须外网能够访问（这里需要配置内网穿透），当支付成功后会调用该API
  notify_url: http://b5x773.natappfree.cc
  # 同步回调地址 必须外网能够访问
  return_url:
  # 网关（注意沙箱网关和正式网关的区别，这里填写沙箱环境下的网关）
  URL: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  # 编码
  CHARSET: UTF-8
  # 返回数据格式
  FORMAT: json
  # 日志地址
  log_path: /log
  # RSA2
  SIGNTYPE: RSA2
