name: Automated API Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: deploy_app_jar #开始部署
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} #服务器ip地址
          username: ${{ secrets.USERNAME }} #服务器ssh用户名
          password: ${{ secrets.PASSWORD }} #服务器ssh密码
          port: ${{ secrets.PORT }} # 服务器ssh端口（默认22）
          run: |
            sleep 120s
            npm install -g apifox-cli
            apifox run https://api.apifox.cn/api/v1/projects/2982605/api-test/ci-config/368475/detail?token=xgJg2kIMA1GXhaTnzM63zW -r html,cli
 