name: Automated API Tests

on:
  push:
    branches: [ "master", "GitActions" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: root
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install Apifox CLI
        run: npm install -g apifox-cli
      
      - name: Running Test Scenario
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: apifox run https://api.apifox.cn/api/v1/projects/2982605/api-test/ci-config/368463/detail?token=x_2Iuvf_-fj9KdnfBlTJ0S -r html,cli